#BK9130B1/connType = Serial
BK9130B1/devcId = /dev/serial/by-path/pci-0000:00:14.0-usb-0:12.3:1.0-port0
#BK9130B2/connType = Serial
BK9130B2/devcId = /dev/serial/by-path/pci-0000:00:14.0-usb-0:12.2:1.0-port0
#BK9184/connType = Serial
BK9184/devcId = /dev/serial/by-path/pci-0000:00:14.0-usb-0:12.1.1:1.0-port0
#BK9184/connType = Serial
BK1697B/devcId = /dev/serial/by-path/pci-0000:00:14.0-usb-0:12.1.4:1.0
BK9130B1/Digital/voltage = 5.0
BK9130B1/Analog/voltage = 8.0
BK9130B2/ClockHigh/voltage = 15.0
BK9130B2/ClockLow/voltage = 15.0
BK1697B/OD/voltage = 38.0
BK9184/HVBias/voltage = 50.0
BK9184/HVBias/current = 0.001
BK9130B1/Heater/voltage = 12.0
BK9130B2/OTM/voltage = 5.0
